/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as DataDeletionRouteImport } from './routes/data-deletion'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedFavoritesRouteImport } from './routes/_authenticated/favorites'
import { Route as AuthenticatedMyPlacesRouteImport } from './routes/_authenticated/my-places'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as PlacesSlugRouteImport } from './routes/places.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminPlacesRouteImport } from './routes/_authenticated/admin/places'
import { Route as AuthenticatedPlacesNewRouteImport } from './routes/_authenticated/places.new'
import { Route as ApiPublicInitialAdminSetupRouteImport } from './routes/api/public/initial-admin-setup'
import { Route as AuthenticatedPlacesIdEditRouteImport } from './routes/_authenticated/places.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DataDeletionRoute = DataDeletionRouteImport.update({
  id: '/data-deletion',
  path: '/data-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavoritesRoute = AuthenticatedFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyPlacesRoute = AuthenticatedMyPlacesRouteImport.update({
  id: '/my-places',
  path: '/my-places',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesSlugRoute = PlacesSlugRouteImport.update({
  id: '/places/$slug',
  path: '/places/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminPlacesRoute =
  AuthenticatedAdminPlacesRouteImport.update({
    id: '/places',
    path: '/places',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedPlacesNewRoute = AuthenticatedPlacesNewRouteImport.update({
  id: '/places/new',
  path: '/places/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicInitialAdminSetupRoute =
  ApiPublicInitialAdminSetupRouteImport.update({
    id: '/api/public/initial-admin-setup',
    path: '/api/public/initial-admin-setup',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPlacesIdEditRoute =
  AuthenticatedPlacesIdEditRouteImport.update({
    id: '/places/$id/edit',
    path: '/places/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/data-deletion': typeof DataDeletionRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/my-places': typeof AuthenticatedMyPlacesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/places/$slug': typeof PlacesSlugRoute
  '/admin/places': typeof AuthenticatedAdminPlacesRoute
  '/places/new': typeof AuthenticatedPlacesNewRoute
  '/api/public/initial-admin-setup': typeof ApiPublicInitialAdminSetupRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/places/$id/edit': typeof AuthenticatedPlacesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/data-deletion': typeof DataDeletionRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/my-places': typeof AuthenticatedMyPlacesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/places/$slug': typeof PlacesSlugRoute
  '/admin/places': typeof AuthenticatedAdminPlacesRoute
  '/places/new': typeof AuthenticatedPlacesNewRoute
  '/api/public/initial-admin-setup': typeof ApiPublicInitialAdminSetupRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/places/$id/edit': typeof AuthenticatedPlacesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/data-deletion': typeof DataDeletionRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/favorites': typeof AuthenticatedFavoritesRoute
  '/_authenticated/my-places': typeof AuthenticatedMyPlacesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/places/$slug': typeof PlacesSlugRoute
  '/_authenticated/admin/places': typeof AuthenticatedAdminPlacesRoute
  '/_authenticated/places/new': typeof AuthenticatedPlacesNewRoute
  '/api/public/initial-admin-setup': typeof ApiPublicInitialAdminSetupRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/places/$id/edit': typeof AuthenticatedPlacesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories'
    | '/cookie-policy'
    | '/data-deletion'
    | '/login'
    | '/privacy-policy'
    | '/register'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/favorites'
    | '/my-places'
    | '/profile'
    | '/auth/callback'
    | '/places/$slug'
    | '/admin/places'
    | '/places/new'
    | '/api/public/initial-admin-setup'
    | '/admin/'
    | '/places/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/cookie-policy'
    | '/data-deletion'
    | '/login'
    | '/privacy-policy'
    | '/register'
    | '/sitemap.xml'
    | '/terms'
    | '/favorites'
    | '/my-places'
    | '/profile'
    | '/auth/callback'
    | '/places/$slug'
    | '/admin/places'
    | '/places/new'
    | '/api/public/initial-admin-setup'
    | '/admin'
    | '/places/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/categories'
    | '/cookie-policy'
    | '/data-deletion'
    | '/login'
    | '/privacy-policy'
    | '/register'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/favorites'
    | '/_authenticated/my-places'
    | '/_authenticated/profile'
    | '/auth/callback'
    | '/places/$slug'
    | '/_authenticated/admin/places'
    | '/_authenticated/places/new'
    | '/api/public/initial-admin-setup'
    | '/_authenticated/admin/'
    | '/_authenticated/places/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CategoriesRoute: typeof CategoriesRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  DataDeletionRoute: typeof DataDeletionRoute
  LoginRoute: typeof LoginRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RegisterRoute: typeof RegisterRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  PlacesSlugRoute: typeof PlacesSlugRoute
  ApiPublicInitialAdminSetupRoute: typeof ApiPublicInitialAdminSetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-deletion': {
      id: '/data-deletion'
      path: '/data-deletion'
      fullPath: '/data-deletion'
      preLoaderRoute: typeof DataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favorites': {
      id: '/_authenticated/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AuthenticatedFavoritesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-places': {
      id: '/_authenticated/my-places'
      path: '/my-places'
      fullPath: '/my-places'
      preLoaderRoute: typeof AuthenticatedMyPlacesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places/$slug': {
      id: '/places/$slug'
      path: '/places/$slug'
      fullPath: '/places/$slug'
      preLoaderRoute: typeof PlacesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/places': {
      id: '/_authenticated/admin/places'
      path: '/places'
      fullPath: '/admin/places'
      preLoaderRoute: typeof AuthenticatedAdminPlacesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/places/new': {
      id: '/_authenticated/places/new'
      path: '/places/new'
      fullPath: '/places/new'
      preLoaderRoute: typeof AuthenticatedPlacesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/initial-admin-setup': {
      id: '/api/public/initial-admin-setup'
      path: '/api/public/initial-admin-setup'
      fullPath: '/api/public/initial-admin-setup'
      preLoaderRoute: typeof ApiPublicInitialAdminSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/places/$id/edit': {
      id: '/_authenticated/places/$id/edit'
      path: '/places/$id/edit'
      fullPath: '/places/$id/edit'
      preLoaderRoute: typeof AuthenticatedPlacesIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminPlacesRoute: typeof AuthenticatedAdminPlacesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminPlacesRoute: AuthenticatedAdminPlacesRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedFavoritesRoute: typeof AuthenticatedFavoritesRoute
  AuthenticatedMyPlacesRoute: typeof AuthenticatedMyPlacesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedPlacesNewRoute: typeof AuthenticatedPlacesNewRoute
  AuthenticatedPlacesIdEditRoute: typeof AuthenticatedPlacesIdEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedFavoritesRoute: AuthenticatedFavoritesRoute,
  AuthenticatedMyPlacesRoute: AuthenticatedMyPlacesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedPlacesNewRoute: AuthenticatedPlacesNewRoute,
  AuthenticatedPlacesIdEditRoute: AuthenticatedPlacesIdEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CategoriesRoute: CategoriesRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  DataDeletionRoute: DataDeletionRoute,
  LoginRoute: LoginRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RegisterRoute: RegisterRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  PlacesSlugRoute: PlacesSlugRoute,
  ApiPublicInitialAdminSetupRoute: ApiPublicInitialAdminSetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
