// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qeleccxzbyqfggwsrzik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFlbGVjY3h6YnlxZmdnd3NyemlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc3ODEzNTMsImV4cCI6MjEwMzM1NzM1M30.P0m-J_0ipJzFSJQPj8_4z09KU8kKQ-8AO5FwfQDqIKw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});